var data = [
  {
    State: "AK",
    Ethnicity: "Asian",
    Total_Population: "55",
    Total_Citizen_Population: "37",
    Total_Registered: "23",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "15",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "AK",
    Ethnicity: "Black",
    Total_Population: "16",
    Total_Citizen_Population: "15",
    Total_Registered: "9",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "8",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "AK",
    Ethnicity: "White",
    Total_Population: "330",
    Total_Citizen_Population: "324",
    Total_Registered: "236",
    Percent_of_Total_Population_Registered: "71.6",
    Percent_of_Citizens_Registered: "73.0",
    Total_Voted: "193",
    Percent_Voted_of_Total_Population: "58.6",
    Percent_Voted_of_Citizens: "59.7"
  },
  {
    State: "AK",
    Ethnicity: "White non-Hispanic",
    Total_Population: "314",
    Total_Citizen_Population: "310",
    Total_Registered: "229",
    Percent_of_Total_Population_Registered: "73.0",
    Percent_of_Citizens_Registered: "73.9",
    Total_Voted: "187",
    Percent_Voted_of_Total_Population: "59.5",
    Percent_Voted_of_Citizens: "60.3"
  },
  {
    State: "AL",
    Ethnicity: "Asian",
    Total_Population: "61",
    Total_Citizen_Population: "37",
    Total_Registered: "13",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "7",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "AL",
    Ethnicity: "Black",
    Total_Population: "976",
    Total_Citizen_Population: "975",
    Total_Registered: "657",
    Percent_of_Total_Population_Registered: "67.2",
    Percent_of_Citizens_Registered: "67.4",
    Total_Voted: "483",
    Percent_Voted_of_Total_Population: "49.4",
    Percent_Voted_of_Citizens: "49.5"
  },
  {
    State: "AL",
    Ethnicity: "White",
    Total_Population: "2,610",
    Total_Citizen_Population: "2,534",
    Total_Registered: "1,774",
    Percent_of_Total_Population_Registered: "68.0",
    Percent_of_Citizens_Registered: "70.0",
    Total_Voted: "1,309",
    Percent_Voted_of_Total_Population: "50.1",
    Percent_Voted_of_Citizens: "51.6"
  },
  {
    State: "AL",
    Ethnicity: "White non-Hispanic",
    Total_Population: "2,494",
    Total_Citizen_Population: "2,470",
    Total_Registered: "1,760",
    Percent_of_Total_Population_Registered: "70.6",
    Percent_of_Citizens_Registered: "71.3",
    Total_Voted: "1,298",
    Percent_Voted_of_Total_Population: "52.1",
    Percent_Voted_of_Citizens: "52.6"
  },
  {
    State: "AR",
    Ethnicity: "Asian",
    Total_Population: "37",
    Total_Citizen_Population: "19",
    Total_Registered: "9",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "6",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "AR",
    Ethnicity: "Black",
    Total_Population: "327",
    Total_Citizen_Population: "317",
    Total_Registered: "178",
    Percent_of_Total_Population_Registered: "54.5",
    Percent_of_Citizens_Registered: "56.1",
    Total_Voted: "132",
    Percent_Voted_of_Total_Population: "40.3",
    Percent_Voted_of_Citizens: "41.6"
  },
  {
    State: "AR",
    Ethnicity: "White",
    Total_Population: "1,833",
    Total_Citizen_Population: "1,765",
    Total_Registered: "1,031",
    Percent_of_Total_Population_Registered: "56.2",
    Percent_of_Citizens_Registered: "58.4",
    Total_Voted: "756",
    Percent_Voted_of_Total_Population: "41.3",
    Percent_Voted_of_Citizens: "42.8"
  },
  {
    State: "AR",
    Ethnicity: "White non-Hispanic",
    Total_Population: "1,678",
    Total_Citizen_Population: "1,676",
    Total_Registered: "995",
    Percent_of_Total_Population_Registered: "59.3",
    Percent_of_Citizens_Registered: "59.3",
    Total_Voted: "737",
    Percent_Voted_of_Total_Population: "43.9",
    Percent_Voted_of_Citizens: "44.0"
  },
  {
    State: "AZ",
    Ethnicity: "Asian",
    Total_Population: "198",
    Total_Citizen_Population: "106",
    Total_Registered: "63",
    Percent_of_Total_Population_Registered: "32.0",
    Percent_of_Citizens_Registered: "59.8",
    Total_Voted: "59",
    Percent_Voted_of_Total_Population: "30.0",
    Percent_Voted_of_Citizens: "56.1"
  },
  {
    State: "AZ",
    Ethnicity: "Black",
    Total_Population: "257",
    Total_Citizen_Population: "222",
    Total_Registered: "114",
    Percent_of_Total_Population_Registered: "44.4",
    Percent_of_Citizens_Registered: "51.5",
    Total_Voted: "104",
    Percent_Voted_of_Total_Population: "40.6",
    Percent_Voted_of_Citizens: "47.0"
  },
  {
    State: "AZ",
    Ethnicity: "White",
    Total_Population: "4,635",
    Total_Citizen_Population: "4,168",
    Total_Registered: "2,968",
    Percent_of_Total_Population_Registered: "64.0",
    Percent_of_Citizens_Registered: "71.2",
    Total_Voted: "2,535",
    Percent_Voted_of_Total_Population: "54.7",
    Percent_Voted_of_Citizens: "60.8"
  },
  {
    State: "AZ",
    Ethnicity: "White non-Hispanic",
    Total_Population: "3,128",
    Total_Citizen_Population: "3,065",
    Total_Registered: "2,272",
    Percent_of_Total_Population_Registered: "72.6",
    Percent_of_Citizens_Registered: "74.1",
    Total_Voted: "2,000",
    Percent_Voted_of_Total_Population: "63.9",
    Percent_Voted_of_Citizens: "65.3"
  },
  {
    State: "CA",
    Ethnicity: "Asian",
    Total_Population: "5,222",
    Total_Citizen_Population: "3,983",
    Total_Registered: "2,061",
    Percent_of_Total_Population_Registered: "39.5",
    Percent_of_Citizens_Registered: "51.7",
    Total_Voted: "1,620",
    Percent_Voted_of_Total_Population: "31.0",
    Percent_Voted_of_Citizens: "40.7"
  },
  {
    State: "CA",
    Ethnicity: "Black",
    Total_Population: "1,912",
    Total_Citizen_Population: "1,845",
    Total_Registered: "1,061",
    Percent_of_Total_Population_Registered: "55.5",
    Percent_of_Citizens_Registered: "57.5",
    Total_Voted: "933",
    Percent_Voted_of_Total_Population: "48.8",
    Percent_Voted_of_Citizens: "50.6"
  },
  {
    State: "CA",
    Ethnicity: "White",
    Total_Population: "21,467",
    Total_Citizen_Population: "18,311",
    Total_Registered: "11,711",
    Percent_of_Total_Population_Registered: "54.6",
    Percent_of_Citizens_Registered: "64.0",
    Total_Voted: "10,005",
    Percent_Voted_of_Total_Population: "46.6",
    Percent_Voted_of_Citizens: "54.6"
  },
  {
    State: "CA",
    Ethnicity: "White non-Hispanic",
    Total_Population: "11,986",
    Total_Citizen_Population: "11,587",
    Total_Registered: "8,005",
    Percent_of_Total_Population_Registered: "66.8",
    Percent_of_Citizens_Registered: "69.1",
    Total_Voted: "7,116",
    Percent_Voted_of_Total_Population: "59.4",
    Percent_Voted_of_Citizens: "61.4"
  },
  {
    State: "CO",
    Ethnicity: "Asian",
    Total_Population: "156",
    Total_Citizen_Population: "93",
    Total_Registered: "75",
    Percent_of_Total_Population_Registered: "47.7",
    Percent_of_Citizens_Registered: "80.6",
    Total_Voted: "66",
    Percent_Voted_of_Total_Population: "42.3",
    Percent_Voted_of_Citizens: "71.5"
  },
  {
    State: "CO",
    Ethnicity: "Black",
    Total_Population: "185",
    Total_Citizen_Population: "170",
    Total_Registered: "73",
    Percent_of_Total_Population_Registered: "39.6",
    Percent_of_Citizens_Registered: "43.1",
    Total_Voted: "51",
    Percent_Voted_of_Total_Population: "27.8",
    Percent_Voted_of_Citizens: "30.3"
  },
  {
    State: "CO",
    Ethnicity: "White",
    Total_Population: "3,911",
    Total_Citizen_Population: "3,666",
    Total_Registered: "2,439",
    Percent_of_Total_Population_Registered: "62.4",
    Percent_of_Citizens_Registered: "66.5",
    Total_Voted: "2,185",
    Percent_Voted_of_Total_Population: "55.9",
    Percent_Voted_of_Citizens: "59.6"
  },
  {
    State: "CO",
    Ethnicity: "White non-Hispanic",
    Total_Population: "3,136",
    Total_Citizen_Population: "3,107",
    Total_Registered: "2,141",
    Percent_of_Total_Population_Registered: "68.3",
    Percent_of_Citizens_Registered: "68.9",
    Total_Voted: "1,945",
    Percent_Voted_of_Total_Population: "62.0",
    Percent_Voted_of_Citizens: "62.6"
  },
  {
    State: "CT",
    Ethnicity: "Asian",
    Total_Population: "142",
    Total_Citizen_Population: "100",
    Total_Registered: "51",
    Percent_of_Total_Population_Registered: "36.1",
    Percent_of_Citizens_Registered: "51.4",
    Total_Voted: "38",
    Percent_Voted_of_Total_Population: "26.5",
    Percent_Voted_of_Citizens: "37.7"
  },
  {
    State: "CT",
    Ethnicity: "Black",
    Total_Population: "319",
    Total_Citizen_Population: "258",
    Total_Registered: "158",
    Percent_of_Total_Population_Registered: "49.6",
    Percent_of_Citizens_Registered: "61.3",
    Total_Voted: "124",
    Percent_Voted_of_Total_Population: "39.0",
    Percent_Voted_of_Citizens: "48.2"
  },
  {
    State: "CT",
    Ethnicity: "White",
    Total_Population: "2,326",
    Total_Citizen_Population: "2,141",
    Total_Registered: "1,483",
    Percent_of_Total_Population_Registered: "63.8",
    Percent_of_Citizens_Registered: "69.3",
    Total_Voted: "1,193",
    Percent_Voted_of_Total_Population: "51.3",
    Percent_Voted_of_Citizens: "55.7"
  },
  {
    State: "CT",
    Ethnicity: "White non-Hispanic",
    Total_Population: "1,934",
    Total_Citizen_Population: "1,888",
    Total_Registered: "1,347",
    Percent_of_Total_Population_Registered: "69.7",
    Percent_of_Citizens_Registered: "71.3",
    Total_Voted: "1,090",
    Percent_Voted_of_Total_Population: "56.4",
    Percent_Voted_of_Citizens: "57.7"
  },
  {
    State: "DC",
    Ethnicity: "Asian",
    Total_Population: "30",
    Total_Citizen_Population: "22",
    Total_Registered: "16",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "13",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "DC",
    Ethnicity: "Black",
    Total_Population: "251",
    Total_Citizen_Population: "228",
    Total_Registered: "163",
    Percent_of_Total_Population_Registered: "65.2",
    Percent_of_Citizens_Registered: "71.7",
    Total_Voted: "123",
    Percent_Voted_of_Total_Population: "48.9",
    Percent_Voted_of_Citizens: "53.7"
  },
  {
    State: "DC",
    Ethnicity: "White",
    Total_Population: "270",
    Total_Citizen_Population: "247",
    Total_Registered: "207",
    Percent_of_Total_Population_Registered: "76.5",
    Percent_of_Citizens_Registered: "83.5",
    Total_Voted: "168",
    Percent_Voted_of_Total_Population: "62.1",
    Percent_Voted_of_Citizens: "67.8"
  },
  {
    State: "DC",
    Ethnicity: "White non-Hispanic",
    Total_Population: "235",
    Total_Citizen_Population: "223",
    Total_Registered: "191",
    Percent_of_Total_Population_Registered: "81.3",
    Percent_of_Citizens_Registered: "85.8",
    Total_Voted: "155",
    Percent_Voted_of_Total_Population: "65.9",
    Percent_Voted_of_Citizens: "69.5"
  },
  {
    State: "DE",
    Ethnicity: "Asian",
    Total_Population: "41",
    Total_Citizen_Population: "28",
    Total_Registered: "15",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "11",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "DE",
    Ethnicity: "Black",
    Total_Population: "163",
    Total_Citizen_Population: "159",
    Total_Registered: "109",
    Percent_of_Total_Population_Registered: "66.5",
    Percent_of_Citizens_Registered: "68.2",
    Total_Voted: "90",
    Percent_Voted_of_Total_Population: "54.8",
    Percent_Voted_of_Citizens: "56.2"
  },
  {
    State: "DE",
    Ethnicity: "White",
    Total_Population: "540",
    Total_Citizen_Population: "513",
    Total_Registered: "340",
    Percent_of_Total_Population_Registered: "62.9",
    Percent_of_Citizens_Registered: "66.2",
    Total_Voted: "264",
    Percent_Voted_of_Total_Population: "48.8",
    Percent_Voted_of_Citizens: "51.4"
  },
  {
    State: "DE",
    Ethnicity: "White non-Hispanic",
    Total_Population: "477",
    Total_Citizen_Population: "468",
    Total_Registered: "316",
    Percent_of_Total_Population_Registered: "66.3",
    Percent_of_Citizens_Registered: "67.6",
    Total_Voted: "247",
    Percent_Voted_of_Total_Population: "51.7",
    Percent_Voted_of_Citizens: "52.7"
  },
  {
    State: "FL",
    Ethnicity: "Asian",
    Total_Population: "454",
    Total_Citizen_Population: "330",
    Total_Registered: "159",
    Percent_of_Total_Population_Registered: "35.0",
    Percent_of_Citizens_Registered: "48.2",
    Total_Voted: "134",
    Percent_Voted_of_Total_Population: "29.4",
    Percent_Voted_of_Citizens: "40.5"
  },
  {
    State: "FL",
    Ethnicity: "Black",
    Total_Population: "2,644",
    Total_Citizen_Population: "2,317",
    Total_Registered: "1,340",
    Percent_of_Total_Population_Registered: "50.7",
    Percent_of_Citizens_Registered: "57.9",
    Total_Voted: "1,094",
    Percent_Voted_of_Total_Population: "41.4",
    Percent_Voted_of_Citizens: "47.2"
  },
  {
    State: "FL",
    Ethnicity: "White",
    Total_Population: "13,425",
    Total_Citizen_Population: "12,154",
    Total_Registered: "7,798",
    Percent_of_Total_Population_Registered: "58.1",
    Percent_of_Citizens_Registered: "64.2",
    Total_Voted: "6,579",
    Percent_Voted_of_Total_Population: "49.0",
    Percent_Voted_of_Citizens: "54.1"
  },
  {
    State: "FL",
    Ethnicity: "White non-Hispanic",
    Total_Population: "9,592",
    Total_Citizen_Population: "9,332",
    Total_Registered: "6,211",
    Percent_of_Total_Population_Registered: "64.8",
    Percent_of_Citizens_Registered: "66.6",
    Total_Voted: "5,315",
    Percent_Voted_of_Total_Population: "55.4",
    Percent_Voted_of_Citizens: "57.0"
  },
  {
    State: "GA",
    Ethnicity: "Asian",
    Total_Population: "318",
    Total_Citizen_Population: "191",
    Total_Registered: "108",
    Percent_of_Total_Population_Registered: "33.9",
    Percent_of_Citizens_Registered: "56.4",
    Total_Voted: "84",
    Percent_Voted_of_Total_Population: "26.3",
    Percent_Voted_of_Citizens: "43.8"
  },
  {
    State: "GA",
    Ethnicity: "Black",
    Total_Population: "2,439",
    Total_Citizen_Population: "2,305",
    Total_Registered: "1,577",
    Percent_of_Total_Population_Registered: "64.7",
    Percent_of_Citizens_Registered: "68.4",
    Total_Voted: "1,374",
    Percent_Voted_of_Total_Population: "56.3",
    Percent_Voted_of_Citizens: "59.6"
  },
  {
    State: "GA",
    Ethnicity: "White",
    Total_Population: "4,949",
    Total_Citizen_Population: "4,686",
    Total_Registered: "3,093",
    Percent_of_Total_Population_Registered: "62.5",
    Percent_of_Citizens_Registered: "66.0",
    Total_Voted: "2,581",
    Percent_Voted_of_Total_Population: "52.2",
    Percent_Voted_of_Citizens: "55.1"
  },
  {
    State: "GA",
    Ethnicity: "White non-Hispanic",
    Total_Population: "4,491",
    Total_Citizen_Population: "4,454",
    Total_Registered: "2,973",
    Percent_of_Total_Population_Registered: "66.2",
    Percent_of_Citizens_Registered: "66.8",
    Total_Voted: "2,496",
    Percent_Voted_of_Total_Population: "55.6",
    Percent_Voted_of_Citizens: "56.1"
  },
  {
    State: "HI",
    Ethnicity: "Asian",
    Total_Population: "480",
    Total_Citizen_Population: "417",
    Total_Registered: "218",
    Percent_of_Total_Population_Registered: "45.4",
    Percent_of_Citizens_Registered: "52.2",
    Total_Voted: "186",
    Percent_Voted_of_Total_Population: "38.7",
    Percent_Voted_of_Citizens: "44.6"
  },
  {
    State: "HI",
    Ethnicity: "Black",
    Total_Population: "22",
    Total_Citizen_Population: "21",
    Total_Registered: "10",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "4",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "HI",
    Ethnicity: "White",
    Total_Population: "237",
    Total_Citizen_Population: "231",
    Total_Registered: "137",
    Percent_of_Total_Population_Registered: "57.9",
    Percent_of_Citizens_Registered: "59.3",
    Total_Voted: "111",
    Percent_Voted_of_Total_Population: "46.8",
    Percent_Voted_of_Citizens: "47.9"
  },
  {
    State: "HI",
    Ethnicity: "White non-Hispanic",
    Total_Population: "211",
    Total_Citizen_Population: "206",
    Total_Registered: "125",
    Percent_of_Total_Population_Registered: "59.3",
    Percent_of_Citizens_Registered: "60.7",
    Total_Voted: "104",
    Percent_Voted_of_Total_Population: "49.3",
    Percent_Voted_of_Citizens: "50.4"
  },
  {
    State: "IA",
    Ethnicity: "Asian",
    Total_Population: "62",
    Total_Citizen_Population: "22",
    Total_Registered: "14",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "12",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "IA",
    Ethnicity: "Black",
    Total_Population: "89",
    Total_Citizen_Population: "76",
    Total_Registered: "47",
    Percent_of_Total_Population_Registered: "52.6",
    Percent_of_Citizens_Registered: "61.3",
    Total_Voted: "41",
    Percent_Voted_of_Total_Population: "46.4",
    Percent_Voted_of_Citizens: "54.1"
  },
  {
    State: "IA",
    Ethnicity: "White",
    Total_Population: "2,192",
    Total_Citizen_Population: "2,119",
    Total_Registered: "1,580",
    Percent_of_Total_Population_Registered: "72.1",
    Percent_of_Citizens_Registered: "74.5",
    Total_Voted: "1,270",
    Percent_Voted_of_Total_Population: "57.9",
    Percent_Voted_of_Citizens: "59.9"
  },
  {
    State: "IA",
    Ethnicity: "White non-Hispanic",
    Total_Population: "2,007",
    Total_Citizen_Population: "1,983",
    Total_Registered: "1,499",
    Percent_of_Total_Population_Registered: "74.7",
    Percent_of_Citizens_Registered: "75.6",
    Total_Voted: "1,206",
    Percent_Voted_of_Total_Population: "60.1",
    Percent_Voted_of_Citizens: "60.8"
  },
  {
    State: "ID",
    Ethnicity: "Asian",
    Total_Population: "33",
    Total_Citizen_Population: "22",
    Total_Registered: "9",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "8",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "ID",
    Ethnicity: "Black",
    Total_Population: "8",
    Total_Citizen_Population: "8",
    Total_Registered: "8",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "6",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "ID",
    Ethnicity: "White",
    Total_Population: "1,214",
    Total_Citizen_Population: "1,163",
    Total_Registered: "708",
    Percent_of_Total_Population_Registered: "58.3",
    Percent_of_Citizens_Registered: "60.9",
    Total_Voted: "555",
    Percent_Voted_of_Total_Population: "45.7",
    Percent_Voted_of_Citizens: "47.7"
  },
  {
    State: "ID",
    Ethnicity: "White non-Hispanic",
    Total_Population: "1,048",
    Total_Citizen_Population: "1,044",
    Total_Registered: "664",
    Percent_of_Total_Population_Registered: "63.3",
    Percent_of_Citizens_Registered: "63.6",
    Total_Voted: "531",
    Percent_Voted_of_Total_Population: "50.6",
    Percent_Voted_of_Citizens: "50.9"
  },
  {
    State: "IL",
    Ethnicity: "Asian",
    Total_Population: "673",
    Total_Citizen_Population: "455",
    Total_Registered: "205",
    Percent_of_Total_Population_Registered: "30.5",
    Percent_of_Citizens_Registered: "45.1",
    Total_Voted: "150",
    Percent_Voted_of_Total_Population: "22.4",
    Percent_Voted_of_Citizens: "33.1"
  },
  {
    State: "IL",
    Ethnicity: "Black",
    Total_Population: "1,334",
    Total_Citizen_Population: "1,274",
    Total_Registered: "861",
    Percent_of_Total_Population_Registered: "64.5",
    Percent_of_Citizens_Registered: "67.6",
    Total_Voted: "723",
    Percent_Voted_of_Total_Population: "54.2",
    Percent_Voted_of_Citizens: "56.8"
  },
  {
    State: "IL",
    Ethnicity: "White",
    Total_Population: "7,564",
    Total_Citizen_Population: "7,078",
    Total_Registered: "4,892",
    Percent_of_Total_Population_Registered: "64.7",
    Percent_of_Citizens_Registered: "69.1",
    Total_Voted: "3,802",
    Percent_Voted_of_Total_Population: "50.3",
    Percent_Voted_of_Citizens: "53.7"
  },
  {
    State: "IL",
    Ethnicity: "White non-Hispanic",
    Total_Population: "6,248",
    Total_Citizen_Population: "6,120",
    Total_Registered: "4,436",
    Percent_of_Total_Population_Registered: "71.0",
    Percent_of_Citizens_Registered: "72.5",
    Total_Voted: "3,494",
    Percent_Voted_of_Total_Population: "55.9",
    Percent_Voted_of_Citizens: "57.1"
  },
  {
    State: "IN",
    Ethnicity: "Asian",
    Total_Population: "138",
    Total_Citizen_Population: "98",
    Total_Registered: "40",
    Percent_of_Total_Population_Registered: "28.9",
    Percent_of_Citizens_Registered: "40.5",
    Total_Voted: "27",
    Percent_Voted_of_Total_Population: "19.7",
    Percent_Voted_of_Citizens: "27.6"
  },
  {
    State: "IN",
    Ethnicity: "Black",
    Total_Population: "484",
    Total_Citizen_Population: "468",
    Total_Registered: "299",
    Percent_of_Total_Population_Registered: "61.8",
    Percent_of_Citizens_Registered: "63.9",
    Total_Voted: "221",
    Percent_Voted_of_Total_Population: "45.7",
    Percent_Voted_of_Citizens: "47.2"
  },
  {
    State: "IN",
    Ethnicity: "White",
    Total_Population: "4,260",
    Total_Citizen_Population: "4,125",
    Total_Registered: "2,723",
    Percent_of_Total_Population_Registered: "63.9",
    Percent_of_Citizens_Registered: "66.0",
    Total_Voted: "2,066",
    Percent_Voted_of_Total_Population: "48.5",
    Percent_Voted_of_Citizens: "50.1"
  },
  {
    State: "IN",
    Ethnicity: "White non-Hispanic",
    Total_Population: "3,937",
    Total_Citizen_Population: "3,921",
    Total_Registered: "2,634",
    Percent_of_Total_Population_Registered: "66.9",
    Percent_of_Citizens_Registered: "67.2",
    Total_Voted: "1,996",
    Percent_Voted_of_Total_Population: "50.7",
    Percent_Voted_of_Citizens: "50.9"
  },
  {
    State: "KS",
    Ethnicity: "Asian",
    Total_Population: "59",
    Total_Citizen_Population: "46",
    Total_Registered: "33",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "33",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "KS",
    Ethnicity: "Black",
    Total_Population: "129",
    Total_Citizen_Population: "125",
    Total_Registered: "65",
    Percent_of_Total_Population_Registered: "50.1",
    Percent_of_Citizens_Registered: "51.9",
    Total_Voted: "58",
    Percent_Voted_of_Total_Population: "44.9",
    Percent_Voted_of_Citizens: "46.5"
  },
  {
    State: "KS",
    Ethnicity: "White",
    Total_Population: "1,880",
    Total_Citizen_Population: "1,777",
    Total_Registered: "1,311",
    Percent_of_Total_Population_Registered: "69.7",
    Percent_of_Citizens_Registered: "73.8",
    Total_Voted: "1,028",
    Percent_Voted_of_Total_Population: "54.7",
    Percent_Voted_of_Citizens: "57.8"
  },
  {
    State: "KS",
    Ethnicity: "White non-Hispanic",
    Total_Population: "1,667",
    Total_Citizen_Population: "1,662",
    Total_Registered: "1,249",
    Percent_of_Total_Population_Registered: "74.9",
    Percent_of_Citizens_Registered: "75.2",
    Total_Voted: "982",
    Percent_Voted_of_Total_Population: "58.9",
    Percent_Voted_of_Citizens: "59.1"
  },
  {
    State: "KY",
    Ethnicity: "Asian",
    Total_Population: "82",
    Total_Citizen_Population: "37",
    Total_Registered: "14",
    Percent_of_Total_Population_Registered: "17.4",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "12",
    Percent_Voted_of_Total_Population: "14.1",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "KY",
    Ethnicity: "Black",
    Total_Population: "248",
    Total_Citizen_Population: "233",
    Total_Registered: "164",
    Percent_of_Total_Population_Registered: "66.2",
    Percent_of_Citizens_Registered: "70.7",
    Total_Voted: "131",
    Percent_Voted_of_Total_Population: "52.8",
    Percent_Voted_of_Citizens: "56.4"
  },
  {
    State: "KY",
    Ethnicity: "White",
    Total_Population: "3,014",
    Total_Citizen_Population: "2,954",
    Total_Registered: "2,194",
    Percent_of_Total_Population_Registered: "72.8",
    Percent_of_Citizens_Registered: "74.3",
    Total_Voted: "1,587",
    Percent_Voted_of_Total_Population: "52.7",
    Percent_Voted_of_Citizens: "53.7"
  },
  {
    State: "KY",
    Ethnicity: "White non-Hispanic",
    Total_Population: "2,928",
    Total_Citizen_Population: "2,921",
    Total_Registered: "2,183",
    Percent_of_Total_Population_Registered: "74.5",
    Percent_of_Citizens_Registered: "74.7",
    Total_Voted: "1,579",
    Percent_Voted_of_Total_Population: "53.9",
    Percent_Voted_of_Citizens: "54.1"
  },
  {
    State: "LA",
    Ethnicity: "Asian",
    Total_Population: "60",
    Total_Citizen_Population: "34",
    Total_Registered: "17",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "9",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "LA",
    Ethnicity: "Black",
    Total_Population: "1,076",
    Total_Citizen_Population: "1,072",
    Total_Registered: "688",
    Percent_of_Total_Population_Registered: "63.9",
    Percent_of_Citizens_Registered: "64.1",
    Total_Voted: "531",
    Percent_Voted_of_Total_Population: "49.4",
    Percent_Voted_of_Citizens: "49.5"
  },
  {
    State: "LA",
    Ethnicity: "White",
    Total_Population: "2,212",
    Total_Citizen_Population: "2,120",
    Total_Registered: "1,501",
    Percent_of_Total_Population_Registered: "67.9",
    Percent_of_Citizens_Registered: "70.8",
    Total_Voted: "1,075",
    Percent_Voted_of_Total_Population: "48.6",
    Percent_Voted_of_Citizens: "50.7"
  },
  {
    State: "LA",
    Ethnicity: "White non-Hispanic",
    Total_Population: "2,047",
    Total_Citizen_Population: "2,023",
    Total_Registered: "1,455",
    Percent_of_Total_Population_Registered: "71.1",
    Percent_of_Citizens_Registered: "71.9",
    Total_Voted: "1,046",
    Percent_Voted_of_Total_Population: "51.1",
    Percent_Voted_of_Citizens: "51.7"
  },
  {
    State: "MA",
    Ethnicity: "Asian",
    Total_Population: "416",
    Total_Citizen_Population: "234",
    Total_Registered: "113",
    Percent_of_Total_Population_Registered: "27.0",
    Percent_of_Citizens_Registered: "48.2",
    Total_Voted: "101",
    Percent_Voted_of_Total_Population: "24.2",
    Percent_Voted_of_Citizens: "43.1"
  },
  {
    State: "MA",
    Ethnicity: "Black",
    Total_Population: "454",
    Total_Citizen_Population: "413",
    Total_Registered: "240",
    Percent_of_Total_Population_Registered: "52.8",
    Percent_of_Citizens_Registered: "58.0",
    Total_Voted: "194",
    Percent_Voted_of_Total_Population: "42.7",
    Percent_Voted_of_Citizens: "47.0"
  },
  {
    State: "MA",
    Ethnicity: "White",
    Total_Population: "4,417",
    Total_Citizen_Population: "4,156",
    Total_Registered: "2,934",
    Percent_of_Total_Population_Registered: "66.4",
    Percent_of_Citizens_Registered: "70.6",
    Total_Voted: "2,397",
    Percent_Voted_of_Total_Population: "54.3",
    Percent_Voted_of_Citizens: "57.7"
  },
  {
    State: "MA",
    Ethnicity: "White non-Hispanic",
    Total_Population: "4,006",
    Total_Citizen_Population: "3,858",
    Total_Registered: "2,737",
    Percent_of_Total_Population_Registered: "68.3",
    Percent_of_Citizens_Registered: "70.9",
    Total_Voted: "2,266",
    Percent_Voted_of_Total_Population: "56.6",
    Percent_Voted_of_Citizens: "58.7"
  },
  {
    State: "MD",
    Ethnicity: "Asian",
    Total_Population: "315",
    Total_Citizen_Population: "217",
    Total_Registered: "142",
    Percent_of_Total_Population_Registered: "44.9",
    Percent_of_Citizens_Registered: "65.1",
    Total_Voted: "94",
    Percent_Voted_of_Total_Population: "29.9",
    Percent_Voted_of_Citizens: "43.4"
  },
  {
    State: "MD",
    Ethnicity: "Black",
    Total_Population: "1,414",
    Total_Citizen_Population: "1,293",
    Total_Registered: "856",
    Percent_of_Total_Population_Registered: "60.5",
    Percent_of_Citizens_Registered: "66.2",
    Total_Voted: "630",
    Percent_Voted_of_Total_Population: "44.5",
    Percent_Voted_of_Citizens: "48.7"
  },
  {
    State: "MD",
    Ethnicity: "White",
    Total_Population: "2,800",
    Total_Citizen_Population: "2,635",
    Total_Registered: "2,021",
    Percent_of_Total_Population_Registered: "72.2",
    Percent_of_Citizens_Registered: "76.7",
    Total_Voted: "1,536",
    Percent_Voted_of_Total_Population: "54.9",
    Percent_Voted_of_Citizens: "58.3"
  },
  {
    State: "MD",
    Ethnicity: "White non-Hispanic",
    Total_Population: "2,466",
    Total_Citizen_Population: "2,421",
    Total_Registered: "1,869",
    Percent_of_Total_Population_Registered: "75.8",
    Percent_of_Citizens_Registered: "77.2",
    Total_Voted: "1,414",
    Percent_Voted_of_Total_Population: "57.3",
    Percent_Voted_of_Citizens: "58.4"
  },
  {
    State: "ME",
    Ethnicity: "Asian",
    Total_Population: "20",
    Total_Citizen_Population: "17",
    Total_Registered: "6",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "6",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "ME",
    Ethnicity: "Black",
    Total_Population: "17",
    Total_Citizen_Population: "11",
    Total_Registered: "5",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "3",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "ME",
    Ethnicity: "White",
    Total_Population: "1,011",
    Total_Citizen_Population: "1,002",
    Total_Registered: "796",
    Percent_of_Total_Population_Registered: "78.7",
    Percent_of_Citizens_Registered: "79.4",
    Total_Voted: "669",
    Percent_Voted_of_Total_Population: "66.2",
    Percent_Voted_of_Citizens: "66.8"
  },
  {
    State: "ME",
    Ethnicity: "White non-Hispanic",
    Total_Population: "1,001",
    Total_Citizen_Population: "994",
    Total_Registered: "788",
    Percent_of_Total_Population_Registered: "78.7",
    Percent_of_Citizens_Registered: "79.2",
    Total_Voted: "666",
    Percent_Voted_of_Total_Population: "66.5",
    Percent_Voted_of_Citizens: "67.0"
  },
  {
    State: "MI",
    Ethnicity: "Asian",
    Total_Population: "242",
    Total_Citizen_Population: "134",
    Total_Registered: "91",
    Percent_of_Total_Population_Registered: "37.5",
    Percent_of_Citizens_Registered: "67.9",
    Total_Voted: "72",
    Percent_Voted_of_Total_Population: "29.9",
    Percent_Voted_of_Citizens: "54.1"
  },
  {
    State: "MI",
    Ethnicity: "Black",
    Total_Population: "1,027",
    Total_Citizen_Population: "1,003",
    Total_Registered: "670",
    Percent_of_Total_Population_Registered: "65.2",
    Percent_of_Citizens_Registered: "66.8",
    Total_Voted: "557",
    Percent_Voted_of_Total_Population: "54.2",
    Percent_Voted_of_Citizens: "55.5"
  },
  {
    State: "MI",
    Ethnicity: "White",
    Total_Population: "6,257",
    Total_Citizen_Population: "6,171",
    Total_Registered: "4,620",
    Percent_of_Total_Population_Registered: "73.8",
    Percent_of_Citizens_Registered: "74.9",
    Total_Voted: "3,724",
    Percent_Voted_of_Total_Population: "59.5",
    Percent_Voted_of_Citizens: "60.4"
  },
  {
    State: "MI",
    Ethnicity: "White non-Hispanic",
    Total_Population: "6,033",
    Total_Citizen_Population: "5,973",
    Total_Registered: "4,526",
    Percent_of_Total_Population_Registered: "75.0",
    Percent_of_Citizens_Registered: "75.8",
    Total_Voted: "3,648",
    Percent_Voted_of_Total_Population: "60.5",
    Percent_Voted_of_Citizens: "61.1"
  },
  {
    State: "MN",
    Ethnicity: "Asian",
    Total_Population: "225",
    Total_Citizen_Population: "157",
    Total_Registered: "78",
    Percent_of_Total_Population_Registered: "34.6",
    Percent_of_Citizens_Registered: "49.7",
    Total_Voted: "68",
    Percent_Voted_of_Total_Population: "30.2",
    Percent_Voted_of_Citizens: "43.3"
  },
  {
    State: "MN",
    Ethnicity: "Black",
    Total_Population: "252",
    Total_Citizen_Population: "194",
    Total_Registered: "128",
    Percent_of_Total_Population_Registered: "50.8",
    Percent_of_Citizens_Registered: "66.1",
    Total_Voted: "106",
    Percent_Voted_of_Total_Population: "42.1",
    Percent_Voted_of_Citizens: "54.7"
  },
  {
    State: "MN",
    Ethnicity: "White",
    Total_Population: "3,632",
    Total_Citizen_Population: "3,537",
    Total_Registered: "2,727",
    Percent_of_Total_Population_Registered: "75.1",
    Percent_of_Citizens_Registered: "77.1",
    Total_Voted: "2,286",
    Percent_Voted_of_Total_Population: "62.9",
    Percent_Voted_of_Citizens: "64.7"
  },
  {
    State: "MN",
    Ethnicity: "White non-Hispanic",
    Total_Population: "3,485",
    Total_Citizen_Population: "3,471",
    Total_Registered: "2,683",
    Percent_of_Total_Population_Registered: "77.0",
    Percent_of_Citizens_Registered: "77.3",
    Total_Voted: "2,249",
    Percent_Voted_of_Total_Population: "64.5",
    Percent_Voted_of_Citizens: "64.8"
  },
  {
    State: "MO",
    Ethnicity: "Asian",
    Total_Population: "55",
    Total_Citizen_Population: "35",
    Total_Registered: "17",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "3",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "MO",
    Ethnicity: "Black",
    Total_Population: "504",
    Total_Citizen_Population: "497",
    Total_Registered: "326",
    Percent_of_Total_Population_Registered: "64.8",
    Percent_of_Citizens_Registered: "65.7",
    Total_Voted: "238",
    Percent_Voted_of_Total_Population: "47.3",
    Percent_Voted_of_Citizens: "47.9"
  },
  {
    State: "MO",
    Ethnicity: "White",
    Total_Population: "4,006",
    Total_Citizen_Population: "3,944",
    Total_Registered: "2,887",
    Percent_of_Total_Population_Registered: "72.1",
    Percent_of_Citizens_Registered: "73.2",
    Total_Voted: "2,227",
    Percent_Voted_of_Total_Population: "55.6",
    Percent_Voted_of_Citizens: "56.5"
  },
  {
    State: "MO",
    Ethnicity: "White non-Hispanic",
    Total_Population: "3,874",
    Total_Citizen_Population: "3,856",
    Total_Registered: "2,839",
    Percent_of_Total_Population_Registered: "73.3",
    Percent_of_Citizens_Registered: "73.6",
    Total_Voted: "2,185",
    Percent_Voted_of_Total_Population: "56.4",
    Percent_Voted_of_Citizens: "56.7"
  },
  {
    State: "MS",
    Ethnicity: "Asian",
    Total_Population: "16",
    Total_Citizen_Population: "14",
    Total_Registered: "3",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "-",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "MS",
    Ethnicity: "Black",
    Total_Population: "798",
    Total_Citizen_Population: "796",
    Total_Registered: "621",
    Percent_of_Total_Population_Registered: "77.8",
    Percent_of_Citizens_Registered: "78.1",
    Total_Voted: "476",
    Percent_Voted_of_Total_Population: "59.6",
    Percent_Voted_of_Citizens: "59.8"
  },
  {
    State: "MS",
    Ethnicity: "White",
    Total_Population: "1,353",
    Total_Citizen_Population: "1,341",
    Total_Registered: "956",
    Percent_of_Total_Population_Registered: "70.6",
    Percent_of_Citizens_Registered: "71.2",
    Total_Voted: "688",
    Percent_Voted_of_Total_Population: "50.9",
    Percent_Voted_of_Citizens: "51.3"
  },
  {
    State: "MS",
    Ethnicity: "White non-Hispanic",
    Total_Population: "1,317",
    Total_Citizen_Population: "1,314",
    Total_Registered: "943",
    Percent_of_Total_Population_Registered: "71.6",
    Percent_of_Citizens_Registered: "71.8",
    Total_Voted: "679",
    Percent_Voted_of_Total_Population: "51.6",
    Percent_Voted_of_Citizens: "51.7"
  },
  {
    State: "MT",
    Ethnicity: "Asian",
    Total_Population: "5",
    Total_Citizen_Population: "4",
    Total_Registered: "3",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "3",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "MT",
    Ethnicity: "Black",
    Total_Population: "4",
    Total_Citizen_Population: "4",
    Total_Registered: "1",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "-",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "MT",
    Ethnicity: "White",
    Total_Population: "769",
    Total_Citizen_Population: "760",
    Total_Registered: "546",
    Percent_of_Total_Population_Registered: "71.0",
    Percent_of_Citizens_Registered: "71.8",
    Total_Voted: "494",
    Percent_Voted_of_Total_Population: "64.3",
    Percent_Voted_of_Citizens: "65.0"
  },
  {
    State: "MT",
    Ethnicity: "White non-Hispanic",
    Total_Population: "747",
    Total_Citizen_Population: "740",
    Total_Registered: "534",
    Percent_of_Total_Population_Registered: "71.5",
    Percent_of_Citizens_Registered: "72.1",
    Total_Voted: "483",
    Percent_Voted_of_Total_Population: "64.7",
    Percent_Voted_of_Citizens: "65.3"
  },
  {
    State: "NC",
    Ethnicity: "Asian",
    Total_Population: "186",
    Total_Citizen_Population: "149",
    Total_Registered: "90",
    Percent_of_Total_Population_Registered: "48.5",
    Percent_of_Citizens_Registered: "60.6",
    Total_Voted: "68",
    Percent_Voted_of_Total_Population: "36.4",
    Percent_Voted_of_Citizens: "45.5"
  },
  {
    State: "NC",
    Ethnicity: "Black",
    Total_Population: "1,685",
    Total_Citizen_Population: "1,646",
    Total_Registered: "1,110",
    Percent_of_Total_Population_Registered: "65.9",
    Percent_of_Citizens_Registered: "67.4",
    Total_Voted: "852",
    Percent_Voted_of_Total_Population: "50.6",
    Percent_Voted_of_Citizens: "51.8"
  },
  {
    State: "NC",
    Ethnicity: "White",
    Total_Population: "5,775",
    Total_Citizen_Population: "5,400",
    Total_Registered: "3,830",
    Percent_of_Total_Population_Registered: "66.3",
    Percent_of_Citizens_Registered: "70.9",
    Total_Voted: "2,903",
    Percent_Voted_of_Total_Population: "50.3",
    Percent_Voted_of_Citizens: "53.8"
  },
  {
    State: "NC",
    Ethnicity: "White non-Hispanic",
    Total_Population: "5,239",
    Total_Citizen_Population: "5,170",
    Total_Registered: "3,721",
    Percent_of_Total_Population_Registered: "71.0",
    Percent_of_Citizens_Registered: "72.0",
    Total_Voted: "2,814",
    Percent_Voted_of_Total_Population: "53.7",
    Percent_Voted_of_Citizens: "54.4"
  },
  {
    State: "ND",
    Ethnicity: "Asian",
    Total_Population: "8",
    Total_Citizen_Population: "3",
    Total_Registered: "-",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "-",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "ND",
    Ethnicity: "Black",
    Total_Population: "14",
    Total_Citizen_Population: "6",
    Total_Registered: "2",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "1",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "ND",
    Ethnicity: "White",
    Total_Population: "499",
    Total_Citizen_Population: "494",
    Total_Registered: "368",
    Percent_of_Total_Population_Registered: "73.7",
    Percent_of_Citizens_Registered: "74.6",
    Total_Voted: "315",
    Percent_Voted_of_Total_Population: "63.1",
    Percent_Voted_of_Citizens: "63.8"
  },
  {
    State: "ND",
    Ethnicity: "White non-Hispanic",
    Total_Population: "488",
    Total_Citizen_Population: "483",
    Total_Registered: "362",
    Percent_of_Total_Population_Registered: "74.2",
    Percent_of_Citizens_Registered: "74.9",
    Total_Voted: "311",
    Percent_Voted_of_Total_Population: "63.7",
    Percent_Voted_of_Citizens: "64.3"
  },
  {
    State: "NE",
    Ethnicity: "Asian",
    Total_Population: "58",
    Total_Citizen_Population: "37",
    Total_Registered: "11",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "8",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "NE",
    Ethnicity: "Black",
    Total_Population: "60",
    Total_Citizen_Population: "59",
    Total_Registered: "26",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "15",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "NE",
    Ethnicity: "White",
    Total_Population: "1,277",
    Total_Citizen_Population: "1,203",
    Total_Registered: "822",
    Percent_of_Total_Population_Registered: "64.4",
    Percent_of_Citizens_Registered: "68.4",
    Total_Voted: "633",
    Percent_Voted_of_Total_Population: "49.6",
    Percent_Voted_of_Citizens: "52.6"
  },
  {
    State: "NE",
    Ethnicity: "White non-Hispanic",
    Total_Population: "1,113",
    Total_Citizen_Population: "1,108",
    Total_Registered: "782",
    Percent_of_Total_Population_Registered: "70.2",
    Percent_of_Citizens_Registered: "70.5",
    Total_Voted: "606",
    Percent_Voted_of_Total_Population: "54.5",
    Percent_Voted_of_Citizens: "54.7"
  },
  {
    State: "NH",
    Ethnicity: "Asian",
    Total_Population: "38",
    Total_Citizen_Population: "23",
    Total_Registered: "15",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "10",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "NH",
    Ethnicity: "Black",
    Total_Population: "16",
    Total_Citizen_Population: "4",
    Total_Registered: "2",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "2",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "NH",
    Ethnicity: "White",
    Total_Population: "1,002",
    Total_Citizen_Population: "978",
    Total_Registered: "698",
    Percent_of_Total_Population_Registered: "69.7",
    Percent_of_Citizens_Registered: "71.4",
    Total_Voted: "556",
    Percent_Voted_of_Total_Population: "55.5",
    Percent_Voted_of_Citizens: "56.8"
  },
  {
    State: "NH",
    Ethnicity: "White non-Hispanic",
    Total_Population: "970",
    Total_Citizen_Population: "956",
    Total_Registered: "683",
    Percent_of_Total_Population_Registered: "70.3",
    Percent_of_Citizens_Registered: "71.4",
    Total_Voted: "545",
    Percent_Voted_of_Total_Population: "56.1",
    Percent_Voted_of_Citizens: "57.0"
  },
  {
    State: "NJ",
    Ethnicity: "Asian",
    Total_Population: "690",
    Total_Citizen_Population: "483",
    Total_Registered: "281",
    Percent_of_Total_Population_Registered: "40.7",
    Percent_of_Citizens_Registered: "58.2",
    Total_Voted: "188",
    Percent_Voted_of_Total_Population: "27.2",
    Percent_Voted_of_Citizens: "38.9"
  },
  {
    State: "NJ",
    Ethnicity: "Black",
    Total_Population: "1,013",
    Total_Citizen_Population: "917",
    Total_Registered: "611",
    Percent_of_Total_Population_Registered: "60.3",
    Percent_of_Citizens_Registered: "66.6",
    Total_Voted: "472",
    Percent_Voted_of_Total_Population: "46.6",
    Percent_Voted_of_Citizens: "51.5"
  },
  {
    State: "NJ",
    Ethnicity: "White",
    Total_Population: "5,227",
    Total_Citizen_Population: "4,788",
    Total_Registered: "3,349",
    Percent_of_Total_Population_Registered: "64.1",
    Percent_of_Citizens_Registered: "69.9",
    Total_Voted: "2,678",
    Percent_Voted_of_Total_Population: "51.2",
    Percent_Voted_of_Citizens: "55.9"
  },
  {
    State: "NJ",
    Ethnicity: "White non-Hispanic",
    Total_Population: "4,081",
    Total_Citizen_Population: "3,944",
    Total_Registered: "2,847",
    Percent_of_Total_Population_Registered: "69.7",
    Percent_of_Citizens_Registered: "72.2",
    Total_Voted: "2,283",
    Percent_Voted_of_Total_Population: "55.9",
    Percent_Voted_of_Citizens: "57.9"
  },
  {
    State: "NM",
    Ethnicity: "Asian",
    Total_Population: "32",
    Total_Citizen_Population: "21",
    Total_Registered: "9",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "7",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "NM",
    Ethnicity: "Black",
    Total_Population: "30",
    Total_Citizen_Population: "27",
    Total_Registered: "15",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "9",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "NM",
    Ethnicity: "White",
    Total_Population: "1,251",
    Total_Citizen_Population: "1,178",
    Total_Registered: "764",
    Percent_of_Total_Population_Registered: "61.1",
    Percent_of_Citizens_Registered: "64.9",
    Total_Voted: "616",
    Percent_Voted_of_Total_Population: "49.2",
    Percent_Voted_of_Citizens: "52.3"
  },
  {
    State: "NM",
    Ethnicity: "White non-Hispanic",
    Total_Population: "644",
    Total_Citizen_Population: "634",
    Total_Registered: "465",
    Percent_of_Total_Population_Registered: "72.2",
    Percent_of_Citizens_Registered: "73.4",
    Total_Voted: "388",
    Percent_Voted_of_Total_Population: "60.3",
    Percent_Voted_of_Citizens: "61.3"
  },
  {
    State: "NV",
    Ethnicity: "Asian",
    Total_Population: "230",
    Total_Citizen_Population: "177",
    Total_Registered: "69",
    Percent_of_Total_Population_Registered: "30.2",
    Percent_of_Citizens_Registered: "39.2",
    Total_Voted: "49",
    Percent_Voted_of_Total_Population: "21.4",
    Percent_Voted_of_Citizens: "27.8"
  },
  {
    State: "NV",
    Ethnicity: "Black",
    Total_Population: "197",
    Total_Citizen_Population: "178",
    Total_Registered: "108",
    Percent_of_Total_Population_Registered: "55.0",
    Percent_of_Citizens_Registered: "60.9",
    Total_Voted: "65",
    Percent_Voted_of_Total_Population: "33.3",
    Percent_Voted_of_Citizens: "36.8"
  },
  {
    State: "NV",
    Ethnicity: "White",
    Total_Population: "1,731",
    Total_Citizen_Population: "1,573",
    Total_Registered: "1,009",
    Percent_of_Total_Population_Registered: "58.3",
    Percent_of_Citizens_Registered: "64.2",
    Total_Voted: "818",
    Percent_Voted_of_Total_Population: "47.2",
    Percent_Voted_of_Citizens: "52.0"
  },
  {
    State: "NV",
    Ethnicity: "White non-Hispanic",
    Total_Population: "1,261",
    Total_Citizen_Population: "1,239",
    Total_Registered: "850",
    Percent_of_Total_Population_Registered: "67.4",
    Percent_of_Citizens_Registered: "68.6",
    Total_Voted: "701",
    Percent_Voted_of_Total_Population: "55.6",
    Percent_Voted_of_Citizens: "56.6"
  },
  {
    State: "NY",
    Ethnicity: "Asian",
    Total_Population: "1,443",
    Total_Citizen_Population: "1,061",
    Total_Registered: "504",
    Percent_of_Total_Population_Registered: "34.9",
    Percent_of_Citizens_Registered: "47.5",
    Total_Voted: "344",
    Percent_Voted_of_Total_Population: "23.8",
    Percent_Voted_of_Citizens: "32.4"
  },
  {
    State: "NY",
    Ethnicity: "Black",
    Total_Population: "2,570",
    Total_Citizen_Population: "2,305",
    Total_Registered: "1,410",
    Percent_of_Total_Population_Registered: "54.9",
    Percent_of_Citizens_Registered: "61.2",
    Total_Voted: "1,182",
    Percent_Voted_of_Total_Population: "46.0",
    Percent_Voted_of_Citizens: "51.3"
  },
  {
    State: "NY",
    Ethnicity: "White",
    Total_Population: "11,157",
    Total_Citizen_Population: "10,070",
    Total_Registered: "6,474",
    Percent_of_Total_Population_Registered: "58.0",
    Percent_of_Citizens_Registered: "64.3",
    Total_Voted: "5,129",
    Percent_Voted_of_Total_Population: "46.0",
    Percent_Voted_of_Citizens: "50.9"
  },
  {
    State: "NY",
    Ethnicity: "White non-Hispanic",
    Total_Population: "9,108",
    Total_Citizen_Population: "8,708",
    Total_Registered: "5,770",
    Percent_of_Total_Population_Registered: "63.4",
    Percent_of_Citizens_Registered: "66.3",
    Total_Voted: "4,604",
    Percent_Voted_of_Total_Population: "50.6",
    Percent_Voted_of_Citizens: "52.9"
  },
  {
    State: "OH",
    Ethnicity: "Asian",
    Total_Population: "207",
    Total_Citizen_Population: "129",
    Total_Registered: "93",
    Percent_of_Total_Population_Registered: "45.1",
    Percent_of_Citizens_Registered: "72.4",
    Total_Voted: "65",
    Percent_Voted_of_Total_Population: "31.3",
    Percent_Voted_of_Citizens: "50.1"
  },
  {
    State: "OH",
    Ethnicity: "Black",
    Total_Population: "1,054",
    Total_Citizen_Population: "1,010",
    Total_Registered: "707",
    Percent_of_Total_Population_Registered: "67.1",
    Percent_of_Citizens_Registered: "70.0",
    Total_Voted: "519",
    Percent_Voted_of_Total_Population: "49.2",
    Percent_Voted_of_Citizens: "51.4"
  },
  {
    State: "OH",
    Ethnicity: "White",
    Total_Population: "7,372",
    Total_Citizen_Population: "7,280",
    Total_Registered: "5,152",
    Percent_of_Total_Population_Registered: "69.9",
    Percent_of_Citizens_Registered: "70.8",
    Total_Voted: "3,889",
    Percent_Voted_of_Total_Population: "52.8",
    Percent_Voted_of_Citizens: "53.4"
  },
  {
    State: "OH",
    Ethnicity: "White non-Hispanic",
    Total_Population: "7,203",
    Total_Citizen_Population: "7,142",
    Total_Registered: "5,058",
    Percent_of_Total_Population_Registered: "70.2",
    Percent_of_Citizens_Registered: "70.8",
    Total_Voted: "3,849",
    Percent_Voted_of_Total_Population: "53.4",
    Percent_Voted_of_Citizens: "53.9"
  },
  {
    State: "OK",
    Ethnicity: "Asian",
    Total_Population: "70",
    Total_Citizen_Population: "50",
    Total_Registered: "23",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "15",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "OK",
    Ethnicity: "Black",
    Total_Population: "195",
    Total_Citizen_Population: "184",
    Total_Registered: "90",
    Percent_of_Total_Population_Registered: "46.1",
    Percent_of_Citizens_Registered: "48.8",
    Total_Voted: "61",
    Percent_Voted_of_Total_Population: "31.2",
    Percent_Voted_of_Citizens: "33.0"
  },
  {
    State: "OK",
    Ethnicity: "White",
    Total_Population: "2,254",
    Total_Citizen_Population: "2,148",
    Total_Registered: "1,422",
    Percent_of_Total_Population_Registered: "63.1",
    Percent_of_Citizens_Registered: "66.2",
    Total_Voted: "1,098",
    Percent_Voted_of_Total_Population: "48.7",
    Percent_Voted_of_Citizens: "51.1"
  },
  {
    State: "OK",
    Ethnicity: "White non-Hispanic",
    Total_Population: "1,957",
    Total_Citizen_Population: "1,951",
    Total_Registered: "1,341",
    Percent_of_Total_Population_Registered: "68.5",
    Percent_of_Citizens_Registered: "68.7",
    Total_Voted: "1,035",
    Percent_Voted_of_Total_Population: "52.9",
    Percent_Voted_of_Citizens: "53.0"
  },
  {
    State: "OR",
    Ethnicity: "Asian",
    Total_Population: "172",
    Total_Citizen_Population: "138",
    Total_Registered: "71",
    Percent_of_Total_Population_Registered: "41.1",
    Percent_of_Citizens_Registered: "51.3",
    Total_Voted: "36",
    Percent_Voted_of_Total_Population: "21.0",
    Percent_Voted_of_Citizens: "26.2"
  },
  {
    State: "OR",
    Ethnicity: "Black",
    Total_Population: "78",
    Total_Citizen_Population: "71",
    Total_Registered: "43",
    Percent_of_Total_Population_Registered: "55.5",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "41",
    Percent_Voted_of_Total_Population: "52.1",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "OR",
    Ethnicity: "White",
    Total_Population: "2,874",
    Total_Citizen_Population: "2,781",
    Total_Registered: "2,059",
    Percent_of_Total_Population_Registered: "71.6",
    Percent_of_Citizens_Registered: "74.0",
    Total_Voted: "1,769",
    Percent_Voted_of_Total_Population: "61.5",
    Percent_Voted_of_Citizens: "63.6"
  },
  {
    State: "OR",
    Ethnicity: "White non-Hispanic",
    Total_Population: "2,584",
    Total_Citizen_Population: "2,569",
    Total_Registered: "1,956",
    Percent_of_Total_Population_Registered: "75.7",
    Percent_of_Citizens_Registered: "76.1",
    Total_Voted: "1,694",
    Percent_Voted_of_Total_Population: "65.6",
    Percent_Voted_of_Citizens: "65.9"
  },
  {
    State: "PA",
    Ethnicity: "Asian",
    Total_Population: "423",
    Total_Citizen_Population: "230",
    Total_Registered: "106",
    Percent_of_Total_Population_Registered: "25.1",
    Percent_of_Citizens_Registered: "46.0",
    Total_Voted: "87",
    Percent_Voted_of_Total_Population: "20.6",
    Percent_Voted_of_Citizens: "37.9"
  },
  {
    State: "PA",
    Ethnicity: "Black",
    Total_Population: "1,059",
    Total_Citizen_Population: "1,028",
    Total_Registered: "653",
    Percent_of_Total_Population_Registered: "61.7",
    Percent_of_Citizens_Registered: "63.5",
    Total_Voted: "562",
    Percent_Voted_of_Total_Population: "53.1",
    Percent_Voted_of_Citizens: "54.7"
  },
  {
    State: "PA",
    Ethnicity: "White",
    Total_Population: "8,277",
    Total_Citizen_Population: "8,073",
    Total_Registered: "5,628",
    Percent_of_Total_Population_Registered: "68.0",
    Percent_of_Citizens_Registered: "69.7",
    Total_Voted: "4,461",
    Percent_Voted_of_Total_Population: "53.9",
    Percent_Voted_of_Citizens: "55.3"
  },
  {
    State: "PA",
    Ethnicity: "White non-Hispanic",
    Total_Population: "7,712",
    Total_Citizen_Population: "7,635",
    Total_Registered: "5,434",
    Percent_of_Total_Population_Registered: "70.5",
    Percent_of_Citizens_Registered: "71.2",
    Total_Voted: "4,323",
    Percent_Voted_of_Total_Population: "56.1",
    Percent_Voted_of_Citizens: "56.6"
  },
  {
    State: "RI",
    Ethnicity: "Asian",
    Total_Population: "26",
    Total_Citizen_Population: "16",
    Total_Registered: "7",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "5",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "RI",
    Ethnicity: "Black",
    Total_Population: "53",
    Total_Citizen_Population: "45",
    Total_Registered: "26",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "16",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "RI",
    Ethnicity: "White",
    Total_Population: "724",
    Total_Citizen_Population: "699",
    Total_Registered: "488",
    Percent_of_Total_Population_Registered: "67.4",
    Percent_of_Citizens_Registered: "69.8",
    Total_Voted: "374",
    Percent_Voted_of_Total_Population: "51.6",
    Percent_Voted_of_Citizens: "53.4"
  },
  {
    State: "RI",
    Ethnicity: "White non-Hispanic",
    Total_Population: "642",
    Total_Citizen_Population: "633",
    Total_Registered: "447",
    Percent_of_Total_Population_Registered: "69.8",
    Percent_of_Citizens_Registered: "70.7",
    Total_Voted: "345",
    Percent_Voted_of_Total_Population: "53.8",
    Percent_Voted_of_Citizens: "54.5"
  },
  {
    State: "SC",
    Ethnicity: "Asian",
    Total_Population: "54",
    Total_Citizen_Population: "29",
    Total_Registered: "19",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "9",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "SC",
    Ethnicity: "Black",
    Total_Population: "1,000",
    Total_Citizen_Population: "996",
    Total_Registered: "646",
    Percent_of_Total_Population_Registered: "64.6",
    Percent_of_Citizens_Registered: "64.9",
    Total_Voted: "519",
    Percent_Voted_of_Total_Population: "51.9",
    Percent_Voted_of_Citizens: "52.1"
  },
  {
    State: "SC",
    Ethnicity: "White",
    Total_Population: "2,790",
    Total_Citizen_Population: "2,677",
    Total_Registered: "1,727",
    Percent_of_Total_Population_Registered: "61.9",
    Percent_of_Citizens_Registered: "64.5",
    Total_Voted: "1,276",
    Percent_Voted_of_Total_Population: "45.7",
    Percent_Voted_of_Citizens: "47.7"
  },
  {
    State: "SC",
    Ethnicity: "White non-Hispanic",
    Total_Population: "2,610",
    Total_Citizen_Population: "2,588",
    Total_Registered: "1,690",
    Percent_of_Total_Population_Registered: "64.8",
    Percent_of_Citizens_Registered: "65.3",
    Total_Voted: "1,257",
    Percent_Voted_of_Total_Population: "48.1",
    Percent_Voted_of_Citizens: "48.6"
  },
  {
    State: "SD",
    Ethnicity: "Asian",
    Total_Population: "5",
    Total_Citizen_Population: "3",
    Total_Registered: "1",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "1",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "SD",
    Ethnicity: "Black",
    Total_Population: "12",
    Total_Citizen_Population: "7",
    Total_Registered: "2",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "1",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "SD",
    Ethnicity: "White",
    Total_Population: "573",
    Total_Citizen_Population: "568",
    Total_Registered: "392",
    Percent_of_Total_Population_Registered: "68.5",
    Percent_of_Citizens_Registered: "69.1",
    Total_Voted: "305",
    Percent_Voted_of_Total_Population: "53.3",
    Percent_Voted_of_Citizens: "53.8"
  },
  {
    State: "SD",
    Ethnicity: "White non-Hispanic",
    Total_Population: "561",
    Total_Citizen_Population: "559",
    Total_Registered: "389",
    Percent_of_Total_Population_Registered: "69.4",
    Percent_of_Citizens_Registered: "69.6",
    Total_Voted: "303",
    Percent_Voted_of_Total_Population: "54.1",
    Percent_Voted_of_Citizens: "54.3"
  },
  {
    State: "TN",
    Ethnicity: "Asian",
    Total_Population: "109",
    Total_Citizen_Population: "97",
    Total_Registered: "32",
    Percent_of_Total_Population_Registered: "29.4",
    Percent_of_Citizens_Registered: "33.0",
    Total_Voted: "29",
    Percent_Voted_of_Total_Population: "26.8",
    Percent_Voted_of_Citizens: "30.2"
  },
  {
    State: "TN",
    Ethnicity: "Black",
    Total_Population: "830",
    Total_Citizen_Population: "801",
    Total_Registered: "484",
    Percent_of_Total_Population_Registered: "58.3",
    Percent_of_Citizens_Registered: "60.4",
    Total_Voted: "368",
    Percent_Voted_of_Total_Population: "44.3",
    Percent_Voted_of_Citizens: "45.9"
  },
  {
    State: "TN",
    Ethnicity: "White",
    Total_Population: "4,156",
    Total_Citizen_Population: "4,015",
    Total_Registered: "2,606",
    Percent_of_Total_Population_Registered: "62.7",
    Percent_of_Citizens_Registered: "64.9",
    Total_Voted: "2,039",
    Percent_Voted_of_Total_Population: "49.1",
    Percent_Voted_of_Citizens: "50.8"
  },
  {
    State: "TN",
    Ethnicity: "White non-Hispanic",
    Total_Population: "3,879",
    Total_Citizen_Population: "3,852",
    Total_Registered: "2,536",
    Percent_of_Total_Population_Registered: "65.4",
    Percent_of_Citizens_Registered: "65.9",
    Total_Voted: "1,991",
    Percent_Voted_of_Total_Population: "51.3",
    Percent_Voted_of_Citizens: "51.7"
  },
  {
    State: "TX",
    Ethnicity: "Asian",
    Total_Population: "1,097",
    Total_Citizen_Population: "736",
    Total_Registered: "397",
    Percent_of_Total_Population_Registered: "36.2",
    Percent_of_Citizens_Registered: "54.0",
    Total_Voted: "288",
    Percent_Voted_of_Total_Population: "26.3",
    Percent_Voted_of_Citizens: "39.1"
  },
  {
    State: "TX",
    Ethnicity: "Black",
    Total_Population: "2,625",
    Total_Citizen_Population: "2,490",
    Total_Registered: "1,580",
    Percent_of_Total_Population_Registered: "60.2",
    Percent_of_Citizens_Registered: "63.4",
    Total_Voted: "1,203",
    Percent_Voted_of_Total_Population: "45.8",
    Percent_Voted_of_Citizens: "48.3"
  },
  {
    State: "TX",
    Ethnicity: "White",
    Total_Population: "16,689",
    Total_Citizen_Population: "14,555",
    Total_Registered: "9,331",
    Percent_of_Total_Population_Registered: "55.9",
    Percent_of_Citizens_Registered: "64.1",
    Total_Voted: "7,158",
    Percent_Voted_of_Total_Population: "42.9",
    Percent_Voted_of_Citizens: "49.2"
  },
  {
    State: "TX",
    Ethnicity: "White non-Hispanic",
    Total_Population: "9,492",
    Total_Citizen_Population: "9,345",
    Total_Registered: "6,686",
    Percent_of_Total_Population_Registered: "70.4",
    Percent_of_Citizens_Registered: "71.5",
    Total_Voted: "5,394",
    Percent_Voted_of_Total_Population: "56.8",
    Percent_Voted_of_Citizens: "57.7"
  },
  {
    State: "UT",
    Ethnicity: "Asian",
    Total_Population: "63",
    Total_Citizen_Population: "44",
    Total_Registered: "26",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "22",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "UT",
    Ethnicity: "Black",
    Total_Population: "31",
    Total_Citizen_Population: "29",
    Total_Registered: "8",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "5",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "UT",
    Ethnicity: "White",
    Total_Population: "2,080",
    Total_Citizen_Population: "1,969",
    Total_Registered: "1,385",
    Percent_of_Total_Population_Registered: "66.6",
    Percent_of_Citizens_Registered: "70.4",
    Total_Voted: "1,171",
    Percent_Voted_of_Total_Population: "56.3",
    Percent_Voted_of_Citizens: "59.5"
  },
  {
    State: "UT",
    Ethnicity: "White non-Hispanic",
    Total_Population: "1,799",
    Total_Citizen_Population: "1,785",
    Total_Registered: "1,293",
    Percent_of_Total_Population_Registered: "71.9",
    Percent_of_Citizens_Registered: "72.4",
    Total_Voted: "1,092",
    Percent_Voted_of_Total_Population: "60.7",
    Percent_Voted_of_Citizens: "61.2"
  },
  {
    State: "VA",
    Ethnicity: "Asian",
    Total_Population: "510",
    Total_Citizen_Population: "368",
    Total_Registered: "226",
    Percent_of_Total_Population_Registered: "44.3",
    Percent_of_Citizens_Registered: "61.4",
    Total_Voted: "169",
    Percent_Voted_of_Total_Population: "33.2",
    Percent_Voted_of_Citizens: "46.0"
  },
  {
    State: "VA",
    Ethnicity: "Black",
    Total_Population: "1,198",
    Total_Citizen_Population: "1,130",
    Total_Registered: "754",
    Percent_of_Total_Population_Registered: "63.0",
    Percent_of_Citizens_Registered: "66.8",
    Total_Voted: "637",
    Percent_Voted_of_Total_Population: "53.2",
    Percent_Voted_of_Citizens: "56.4"
  },
  {
    State: "VA",
    Ethnicity: "White",
    Total_Population: "4,496",
    Total_Citizen_Population: "4,094",
    Total_Registered: "3,065",
    Percent_of_Total_Population_Registered: "68.2",
    Percent_of_Citizens_Registered: "74.9",
    Total_Voted: "2,412",
    Percent_Voted_of_Total_Population: "53.7",
    Percent_Voted_of_Citizens: "58.9"
  },
  {
    State: "VA",
    Ethnicity: "White non-Hispanic",
    Total_Population: "3,874",
    Total_Citizen_Population: "3,808",
    Total_Registered: "2,924",
    Percent_of_Total_Population_Registered: "75.5",
    Percent_of_Citizens_Registered: "76.8",
    Total_Voted: "2,314",
    Percent_Voted_of_Total_Population: "59.7",
    Percent_Voted_of_Citizens: "60.8"
  },
  {
    State: "VT",
    Ethnicity: "Asian",
    Total_Population: "5",
    Total_Citizen_Population: "4",
    Total_Registered: "3",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "3",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "VT",
    Ethnicity: "Black",
    Total_Population: "4",
    Total_Citizen_Population: "4",
    Total_Registered: "2",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "1",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "VT",
    Ethnicity: "White",
    Total_Population: "478",
    Total_Citizen_Population: "473",
    Total_Registered: "330",
    Percent_of_Total_Population_Registered: "68.9",
    Percent_of_Citizens_Registered: "69.7",
    Total_Voted: "263",
    Percent_Voted_of_Total_Population: "55.0",
    Percent_Voted_of_Citizens: "55.6"
  },
  {
    State: "VT",
    Ethnicity: "White non-Hispanic",
    Total_Population: "472",
    Total_Citizen_Population: "466",
    Total_Registered: "323",
    Percent_of_Total_Population_Registered: "68.6",
    Percent_of_Citizens_Registered: "69.4",
    Total_Voted: "258",
    Percent_Voted_of_Total_Population: "54.6",
    Percent_Voted_of_Citizens: "55.3"
  },
  {
    State: "WA",
    Ethnicity: "Asian",
    Total_Population: "530",
    Total_Citizen_Population: "356",
    Total_Registered: "262",
    Percent_of_Total_Population_Registered: "49.4",
    Percent_of_Citizens_Registered: "73.4",
    Total_Voted: "224",
    Percent_Voted_of_Total_Population: "42.2",
    Percent_Voted_of_Citizens: "62.8"
  },
  {
    State: "WA",
    Ethnicity: "Black",
    Total_Population: "232",
    Total_Citizen_Population: "232",
    Total_Registered: "155",
    Percent_of_Total_Population_Registered: "66.8",
    Percent_of_Citizens_Registered: "66.8",
    Total_Voted: "103",
    Percent_Voted_of_Total_Population: "44.2",
    Percent_Voted_of_Citizens: "44.2"
  },
  {
    State: "WA",
    Ethnicity: "White",
    Total_Population: "4,663",
    Total_Citizen_Population: "4,314",
    Total_Registered: "3,219",
    Percent_of_Total_Population_Registered: "69.0",
    Percent_of_Citizens_Registered: "74.6",
    Total_Voted: "2,736",
    Percent_Voted_of_Total_Population: "58.7",
    Percent_Voted_of_Citizens: "63.4"
  },
  {
    State: "WA",
    Ethnicity: "White non-Hispanic",
    Total_Population: "3,995",
    Total_Citizen_Population: "3,905",
    Total_Registered: "2,983",
    Percent_of_Total_Population_Registered: "74.7",
    Percent_of_Citizens_Registered: "76.4",
    Total_Voted: "2,558",
    Percent_Voted_of_Total_Population: "64.0",
    Percent_Voted_of_Citizens: "65.5"
  },
  {
    State: "WI",
    Ethnicity: "Asian",
    Total_Population: "89",
    Total_Citizen_Population: "79",
    Total_Registered: "52",
    Percent_of_Total_Population_Registered: "58.6",
    Percent_of_Citizens_Registered: "66.0",
    Total_Voted: "52",
    Percent_Voted_of_Total_Population: "58.6",
    Percent_Voted_of_Citizens: "66.0"
  },
  {
    State: "WI",
    Ethnicity: "Black",
    Total_Population: "264",
    Total_Citizen_Population: "239",
    Total_Registered: "137",
    Percent_of_Total_Population_Registered: "51.7",
    Percent_of_Citizens_Registered: "57.1",
    Total_Voted: "110",
    Percent_Voted_of_Total_Population: "41.7",
    Percent_Voted_of_Citizens: "46.0"
  },
  {
    State: "WI",
    Ethnicity: "White",
    Total_Population: "3,948",
    Total_Citizen_Population: "3,865",
    Total_Registered: "2,883",
    Percent_of_Total_Population_Registered: "73.0",
    Percent_of_Citizens_Registered: "74.6",
    Total_Voted: "2,574",
    Percent_Voted_of_Total_Population: "65.2",
    Percent_Voted_of_Citizens: "66.6"
  },
  {
    State: "WI",
    Ethnicity: "White non-Hispanic",
    Total_Population: "3,782",
    Total_Citizen_Population: "3,759",
    Total_Registered: "2,815",
    Percent_of_Total_Population_Registered: "74.5",
    Percent_of_Citizens_Registered: "74.9",
    Total_Voted: "2,514",
    Percent_Voted_of_Total_Population: "66.5",
    Percent_Voted_of_Citizens: "66.9"
  },
  {
    State: "WV",
    Ethnicity: "Asian",
    Total_Population: "17",
    Total_Citizen_Population: "6",
    Total_Registered: "4",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "3",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "WV",
    Ethnicity: "Black",
    Total_Population: "49",
    Total_Citizen_Population: "47",
    Total_Registered: "19",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "12",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "WV",
    Ethnicity: "White",
    Total_Population: "1,312",
    Total_Citizen_Population: "1,303",
    Total_Registered: "856",
    Percent_of_Total_Population_Registered: "65.2",
    Percent_of_Citizens_Registered: "65.7",
    Total_Voted: "585",
    Percent_Voted_of_Total_Population: "44.6",
    Percent_Voted_of_Citizens: "44.9"
  },
  {
    State: "WV",
    Ethnicity: "White non-Hispanic",
    Total_Population: "1,291",
    Total_Citizen_Population: "1,286",
    Total_Registered: "847",
    Percent_of_Total_Population_Registered: "65.6",
    Percent_of_Citizens_Registered: "65.9",
    Total_Voted: "582",
    Percent_Voted_of_Total_Population: "45.1",
    Percent_Voted_of_Citizens: "45.2"
  },
  {
    State: "WY",
    Ethnicity: "Asian",
    Total_Population: "3",
    Total_Citizen_Population: "1",
    Total_Registered: "-",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "-",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "WY",
    Ethnicity: "Black",
    Total_Population: "5",
    Total_Citizen_Population: "4",
    Total_Registered: "3",
    Percent_of_Total_Population_Registered: "<1.0",
    Percent_of_Citizens_Registered: "<1.0",
    Total_Voted: "2",
    Percent_Voted_of_Total_Population: "<1.0",
    Percent_Voted_of_Citizens: "<1.0"
  },
  {
    State: "WY",
    Ethnicity: "White",
    Total_Population: "408",
    Total_Citizen_Population: "402",
    Total_Registered: "259",
    Percent_of_Total_Population_Registered: "63.6",
    Percent_of_Citizens_Registered: "64.5",
    Total_Voted: "214",
    Percent_Voted_of_Total_Population: "52.5",
    Percent_Voted_of_Citizens: "53.2"
  },
  {
    State: "WY",
    Ethnicity: "White non-Hispanic",
    Total_Population: "369",
    Total_Citizen_Population: "368",
    Total_Registered: "244",
    Percent_of_Total_Population_Registered: "66.0",
    Percent_of_Citizens_Registered: "66.3",
    Total_Voted: "202",
    Percent_Voted_of_Total_Population: "54.7",
    Percent_Voted_of_Citizens: "54.9"
  }
 ]